### PR TITLE
Fix path to tar on Mac OSX

### PR DESCRIPTION
**Pull request by Sauraus**
Fixes: https://github.com/burtlo/ark/issues/88

### CODE REVIEW

**Comment by harmon** [comment]
+1

Mac 10.10.3:

```
$ which tar
/usr/bin/tar
```

**Comment by Sauraus** [comment]
Any chance of getting this included any time soon? :)

**Comment by Sauraus** [comment]
So what will it take to get this merged?

**Comment by Sauraus** [comment]
Is anyone actually maintaining this cookbook still or is it dead?

**Comment by dwmarshall** [comment]
I'd like to offer some assistance, but I'm still coming up to speed on how best to do that. See #118 for an example of my immediate impediments.

**Comment by Sauraus** [comment]
Well I've actually decided to abandon any hope of these pull request being merged, and will retain my own fork with it's release branch.

**Comment by dwmarshall** [comment]
@burtlo made me a collaborator, so I can merge pull requests! However, I'm not going to merge anything until the Travis builds are passing. If you know anything about how to move that along, I'm sure all the users of the cookbook would be grateful.

**Comment by tas50** [comment]
@Sauraus If you want to rebase this and remove the version bump I'd love to get it merged in

**Comment by tas50** [comment]
I made this same change here so I can get it out as part of 0.10 https://github.com/burtlo/ark/commit/e5561bb0c96e771237ce49cb994fcf08c1b56d77

**Pull request closed without merging**
