### PR TITLE
Release 0.10.0

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by tas50** [comment]
@burtlo @dwmarshall Let me know what you think.  I'd love to get this out first thing in the morning

**Comment by dwmarshall** [comment]
This is awesome. It's been a pleasure to watch my very limited Chef knowledge refactored so thoroughly and professionally.

image

**Comment by dwmarshall** [comment]
I haven't heard from @burtlo in a long while, so I think we should merge and cut a new release, once the conflict is resolved.

**Comment by tas50** [comment]
I think I'm actually going to bump this to 1.0.0, but I'm working on an issue with FreeBSD right now.  It was broken before, but I'd like to fix it if possible.

**Pull request closed without merging**
